# Change these first
owner: lichangwei # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Gaiaworks
    url: https://www.gaiaworks.cn

status-website:
  baseUrl: /updatime
  name: Your Status Website

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
